"""
Automated Test & Verification Script for CyberHelp Flask Application
"""
import unittest
import json
from app import app
from db import get_db

class CyberHelpTestCase(unittest.TestCase):
    def setUp(self):
        app.config['TESTING'] = True
        self.client = app.test_client()

    def test_public_routes(self):
        routes = ['/', '/awareness', '/scams', '/tools', '/quiz', '/faqs', '/reporting', '/chatbot']
        for r in routes:
            resp = self.client.get(r)
            self.assertEqual(resp.status_code, 200, f"Route {r} failed with status {resp.status_code}")
            print(f"[PASS] GET {r} -> 200 OK")

    def test_url_checker_api(self):
        # Test safe url
        resp = self.client.post('/api/check-url', 
                                data=json.dumps({'url': 'https://cybercrime.gov.in'}),
                                content_type='application/json')
        self.assertEqual(resp.status_code, 200)
        data = resp.get_json()
        self.assertEqual(data['risk_score'], 0)
        print("[PASS] URL Checker: Safe domain detected properly.")

        # Test phishing heuristic url
        resp2 = self.client.post('/api/check-url',
                                 data=json.dumps({'url': 'http://secure-sbi-online.update-login.xyz/login.php'}),
                                 content_type='application/json')
        self.assertEqual(resp2.status_code, 200)
        data2 = resp2.get_json()
        self.assertGreaterEqual(data2['risk_score'], 50)
        self.assertIn('DANGEROUS', data2['verdict'])
        print("[PASS] URL Checker: Phishing domain flagged with high risk score.")

    def test_quiz_submission_api(self):
        submission = {
            'answers': {
                '1': 'C',
                '2': 'B',
                '3': 'B',
                '4': 'B',
                '5': 'C'
            }
        }
        resp = self.client.post('/api/quiz/submit',
                                data=json.dumps(submission),
                                content_type='application/json')
        self.assertEqual(resp.status_code, 200)
        data = resp.get_json()
        self.assertEqual(data['score'], 5)
        self.assertGreaterEqual(data['total'], 5)
        print(f"[PASS] Quiz Submission API: Verified score {data['score']}/{data['total']} ({data['percentage']}%)")

    def test_chatbot_api(self):
        resp = self.client.post('/api/chat',
                                data=json.dumps({'message': 'I received a message saying my electricity bill is unpaid. Is it a scam?'}),
                                content_type='application/json')
        self.assertEqual(resp.status_code, 200)
        data = resp.get_json()
        self.assertTrue('reply' in data)
        self.assertTrue(len(data['reply']) > 20)
        print(f"[PASS] Chatbot API: Received response ({data.get('source', '')})")

    def test_admin_auth_and_crud(self):
        # Test login
        resp = self.client.post('/admin/login', data={'username': 'admin', 'password': 'admin123'}, follow_redirects=True)
        self.assertEqual(resp.status_code, 200)
        self.assertIn(b'Helpdesk Content', resp.data)
        print("[PASS] Admin Login: Successfully authenticated.")

        # Test creating awareness article
        create_resp = self.client.post('/admin/awareness', data={
            'action': 'create',
            'title': 'Automated Test Article',
            'category': 'Test Category',
            'description': 'This is a test description generated by automated verification test.'
        }, follow_redirects=True)
        self.assertEqual(create_resp.status_code, 200)
        self.assertIn(b'Automated Test Article', create_resp.data)
        print("[PASS] Admin CRUD: Created awareness guide.")

        # Clean up test article
        conn = get_db()
        conn.execute("DELETE FROM awareness_content WHERE title = 'Automated Test Article'")
        conn.commit()
        conn.close()
        print("[PASS] Admin CRUD: Cleanup verified.")

if __name__ == '__main__':
    unittest.main()
